[package]
name = "hello_guest"
version.workspace = true
edition.workspace = true

[dependencies]
risc0-zkvm = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.2"
serde_json = "1.0"

[[bin]]
name = "hello_guest"
path = "src/bin/hello_guest.rs"