[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
risc0-zkvm = { version = "1.0", features = ["std"] }
methods = { path = "../methods" }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.2"